version: "3"
services:
  web:
    image: vpantiushenko/ipcheck5
    build: .
    environment:
      - containerId={{.Task.Slot}}
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
    - "3000:3000"
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - data:/data/db
    ports:
      - "27017:27017"
volumes:
  data:
    driver: local
